// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6otGQ3MVcDQyn9Jy5fFVPkQ2XCMVgQDI',
    appId: '1:616540584942:web:002ea1862d13dc67b16cff',
    messagingSenderId: '616540584942',
    projectId: 'tayyab-chat',
    authDomain: 'tayyab-chat.firebaseapp.com',
    storageBucket: 'tayyab-chat.firebasestorage.app',
    measurementId: 'G-DWPXT4RCL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMHqLU2rO-mROBcgcni6FUW1eM2VTA8gQ',
    appId: '1:616540584942:android:62460928f58c27feb16cff',
    messagingSenderId: '616540584942',
    projectId: 'tayyab-chat',
    storageBucket: 'tayyab-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZzsYKvwofircyXfmR9-FKdqB-LLhonzk',
    appId: '1:616540584942:ios:8db45d74a70ad5ebb16cff',
    messagingSenderId: '616540584942',
    projectId: 'tayyab-chat',
    storageBucket: 'tayyab-chat.firebasestorage.app',
    iosBundleId: 'com.example.tayyabChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZzsYKvwofircyXfmR9-FKdqB-LLhonzk',
    appId: '1:616540584942:ios:8db45d74a70ad5ebb16cff',
    messagingSenderId: '616540584942',
    projectId: 'tayyab-chat',
    storageBucket: 'tayyab-chat.firebasestorage.app',
    iosBundleId: 'com.example.tayyabChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6otGQ3MVcDQyn9Jy5fFVPkQ2XCMVgQDI',
    appId: '1:616540584942:web:e6d16cc3970850beb16cff',
    messagingSenderId: '616540584942',
    projectId: 'tayyab-chat',
    authDomain: 'tayyab-chat.firebaseapp.com',
    storageBucket: 'tayyab-chat.firebasestorage.app',
    measurementId: 'G-00G2LRZSLG',
  );

}